### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by rhyolight** [fxpresso/tidbit#2]

**Comment by cogmission** [comment]
Fixed

**Comment by cogmission** [comment]
Thanks Matt! :+1:

**Comment by rhyolight** [comment]
Are you sure AGPL is the right license for this software? If it is a general purpose library, you might want to make it less restrictive. Up to you, but be sure to read the GPL and make sure it fits your needs.

**Comment by cogmission** [comment]
Ok I'll review this later... I have to run right now... Thanks!

On Fri, Oct 9, 2015 at 1:47 PM, Matthew Taylor notifications@github.com
wrote:

> Are you sure AGPL is the right license for this software? If it is a
> general purpose library, you might want to make it less restrictive. Up to
> you, but be sure to read the GPL and make sure it fits your needs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fxpresso/tidbit/issues/2#issuecomment-146959074.

## 

_With kind regards,_

David Ray
Java Solutions Architect

_Cortical.io http://cortical.io/_
Sponsor of:  HTM.java https://github.com/numenta/htm.java

d.ray@cortical.io
http://cortical.io
