### ISSUE TITLE
Nullpointer Exception when hitting show/hide button before animation is done

### ISSUE THREAD

**Issue by flinkgutt** [fxpresso/tidbit#4]
Open the demo, try to click on the button, then hit it again as soon as the animation starts but before it finishes.

**Comment by cogmission** [comment]
Thanks for giving it a try! :+1: 

Yeah it's just a demo not an app - but I'll have a look so others know how to interact with the animation aspects.
Cheers,
David

**Comment by cogmission** [comment]
@flinkgutt Let me know how this solution works for you? Thanks for reporting this... :+1:

**Comment by flinkgutt** [comment]
It works fine :-)

**Comment by cogmission** [comment]
Good job @flinkgutt , Thank you! :+1:
